esphome:
  name: "${devicename}"
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32.git

esp32:
  variant: esp32s3
  board: lolin_s3_mini
  framework:
    type: arduino
    version: latest

# Enable logging
logger:

light:
  - platform: neopixelbus
    type: GRB
    variant: 800KBPS
    pin: 47
    num_leds: 1
    name: "Internal RGB LED"
    icon: mdi:led-outline
    id: "${device_id}_rgb_led"
    entity_category: config
    restore_mode: ALWAYS_OFF
    default_transition_length: 500ms
    method:
      type: esp32_rmt
      channel: 0
