- alias: "Desk up"
  trigger:
    platform: numeric_state
    entity_id: sensor.desk_watts
    above: 100
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.desk_up

- alias: "Desk down"
  trigger:
    platform: numeric_state
    entity_id: sensor.desk_watts
    above: 10
    below: 100
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.desk_up

- alias: "Turn on basement lights with TV"
  trigger:
    platform: state
    entity_id: switch.basement_tv
    from: "off"
    to: "on"
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.front_left_light_basement_42
      - light.right_rear_lamp_basement_41

- alias: "Turn on office closet lamp on motion"
  trigger:
    platform: state
    entity_id: binary_sensor.office_4_in_1_sensor_58
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.office_closet_relay

- alias: "Turn off office closet lamp on no motion"
  trigger:
    platform: state
    entity_id: binary_sensor.office_4_in_1_sensor_58
    to: "off"
  action:
    service: switch.turn_off
    entity_id: switch.office_closet_relay
