- alias: "Notify when washing machine is done"
  trigger:
    platform: state
    entity_id: sensor.washing_machine_status
    to: 'Off'
  action:
    - service: notify.telegram
      data:
        message: "Washing machine is done!"

- alias: "Notify when washing machine enters spin cycle, almost done"
  trigger:
    platform: state
    entity_id: sensor.washing_machine_status
    to: 'Spin Cycle'
  action:
    - service: notify.telegram
      data:
        message: "Washing machine is in the spin cycle, almost done!"

- alias: "Desk up"
  trigger:
    platform: numeric_state
    entity_id: sensor.desk_watts
    above: 100
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.desk_up

- alias: "Desk down"
  trigger:
    platform: numeric_state
    entity_id: sensor.desk_watts
    above: 10
    below: 100
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.desk_up

- alias: "Office Humidistat - On"
  trigger:
    platform: numeric_state
    entity_id: sensor.office_humidity_bme280
    below: 30
    for:
      minutes: 5
  action:
   - service: switch.turn_on
     data:
       entity_id: switch.humidifier_101

- alias: "Office Humidistat - Off"
  trigger:
    platform: numeric_state
    entity_id: sensor.office_humidity_bme280
    above: 35
    for:
      minutes: 1
  action:
   - service: switch.turn_off
     data:
       entity_id: switch.humidifier_101

- alias: "Main Floor Humidistat - On"
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_humidity
    below: 40
    for:
      minutes: 5
  action:
   - service: switch.turn_on
     data:
       entity_id: switch.humidifier_lw45_154

- alias: "Main Floor Humidistat - Off"
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_humidity
    above: 45
    for:
      minutes: 1
  action:
   - service: switch.turn_off
     data:
       entity_id: switch.humidifier_lw45_154

- alias: "Turn on basement lights with projector"
  trigger:
    platform: state
    entity_id: switch.projector
    from: "off"
    to: "on"
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.front_left_light_basement_42
      - light.right_rear_lamp_basement_41
