homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 103
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables prometheus exporter
prometheus:
  namespace: hass

# Send notifications to Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
     - "-396790894"

notify:
 - name: "telegram"
   platform: telegram
   chat_id: "-396790894"

recorder:
  db_url: !env_var DB_URL

vera:
  vera_controller_url: http://172.19.74.180:3480
  exclude:
    # Office
    - 40 # office remote, dead battery, but might use one day, so not unpaired.
    - 58 # office 4 in 1 parent device
    - 66 # Motion sensor
    - 67 # Motion sensor 1
    - 68 # Motion sensor 2
    - 74 # Fake smoke sensor
    - 75 # Motion sensor 3
    # Garage
    - 31 # GC100
    - 34 # GC100 relay
    - 32 # Left garage door relay
    - 33 # Right garage door relay
    - 89 # Right garage door sensor
    - 90 # Left garage door sensor

vacuum:
  - platform: roomba
    host: Roomba-3143C91082324790.oneill.net
    username: 3143C91082324790
    password: !secret roomba_password
    name: "Lord Derpington"

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor doorbell:
  platform: ring

camera doorbell:
  platform: ring

sensor doorbell:
 platform: ring

homekit:
  filter:
    exclude_entities:
      - switch.luser_36
      - switch.k2_98
      - switch.k3_99
      - switch.washing_machine_107
      - switch.sump_pump_20
      - switch.washlet_77

http:
  base_url: https://hass.k.oneill.net

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: rest
    resource: "http://veraplus.oneill.net:3480/data_request?id=variableget&DeviceNum=36&serviceId=urn:micasaverde-com:serviceId:EnergyMetering1&Variable=Watts"
    method: GET
    name: Power usage - luser
    unit_of_measurement: "W"
  - platform: template
    sensors:
      battery_front_door_lock:
        friendly_name: "Front Door Lock Battery"
        value_template: '{{ states.lock.front_door_lock_10.attributes.battery_level }}'
        unit_of_measurement: "%"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
