default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 103
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

ios:

recorder:
  db_url: !env_var DB_URL

# Enables prometheus exporter
prometheus:
  namespace: hass

# Send notifications to Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
     - "-396790894"

notify:
- name: "telegram"
  platform: telegram
  chat_id: "-396790894"
- name: "opsgenie"
  platform: smtp
  sender: clayton@oneill.net
  recipient: email1@fnord.opsgenie.net
  server: smtp.gmail.com
  username: clayton.oneill@gmail.com
  password: !secret gmail_smtp_password

#netatmo:
#  username: clayton@oneill.net
#  password: !secret netatmo_password
#  api_key: !secret netatmo_api_key
#  secret_key: !secret netatmo_secret_key

vera:
  vera_controller_url: http://172.19.74.180:3480
  exclude:
    # Office
    - 40 # office remote, dead battery, but might use one day, so not unpaired.
    - 58 # office 4 in 1 parent device
    - 66 # Motion sensor
    - 67 # Motion sensor 1
    - 68 # Motion sensor 2
    - 74 # Fake smoke sensor
    - 75 # Motion sensor 3
    # Garage
    - 31 # GC100
    - 34 # GC100 relay
    - 32 # Left garage door relay
    - 33 # Right garage door relay
    - 89 # Right garage door sensor
    - 90 # Left garage door sensor
  lights:
    - 8  # Garage overhead lights
    - 19 # Office Floor Lamp
    - 106 # Main floor bathroom light

device_tracker:
  - platform: mqtt
    devices:
      clayton_phone_first_floor: "monitor/first-floor/claytons_phone/device_tracker"
      mary_phone_first_floor: "monitor/first-floor/marys_phone/device_tracker"
      paul_phone_first_floor: "monitor/first-floor/pauls_phone/device_tracker"

person:

logger:
  default: info

homekit:
  filter:
    include_entities: &entity_whitelist
    - light.bathroom_light_106
    - light.dining_room_light_108
    - light.family_room_standing_lamp_44
    - light.front_left_light_basement_42
    - light.garage_overhead_lights_8
    - light.office_floor_lamp_19
    - light.office_light_76
    - light.right_rear_lamp_basement_41
    - lock.front_door_lock_10
    - lock.garage_door_lock_88
    - lock.left_garage_door_70
    - lock.right_garage_door_72
    - sensor.garage_humidity
    - sensor.garage_temperature
    - sensor.netatmo_indoor_humidity
    - sensor.netatmo_indoor_temperature
    - sensor.netatmo_outdoor_humidity
    - sensor.netatmo_outdoor_temperature
    # Harmony
    - switch.projector
    - switch.appletv
    - switch.xbox
    - switch.playstation

# Cloud
cloud:
  alexa:
    filter:
      include_entities: *entity_whitelist



mqtt:
  broker: mosquitto
  username: hass
  password: !secret mqtt_password

http:
  base_url: https://hass.k.oneill.net

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

climate:
  - platform: generic_thermostat
    name: Office Thermostat
    heater: switch.office_heater_37
    target_sensor: sensor.office_temperature_bme280
    precision: 0.1
    min_temp: 60
    max_temp: 85
    hot_tolerance: 0

switch:
- platform: template
  switches:
    projector:
      friendly_name: "Projector"
      value_template: "{{ not is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Watch Apple TV"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
    appletv:
      friendly_name: "Apple TV"
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Apple TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Watch Apple TV"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
    xbox:
      friendly_name: "XBox"
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Xbox One') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Play Xbox One"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
    playstation:
      friendly_name: "Playstation"
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play PS4') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Play PS4"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub

# Sensors
sensor:
  - platform: awair
    access_token: !secret awair_token
  - platform: template
    sensors:
      luser_watts:
        value_template: >-
          {{ state_attr('switch.luser_36', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      k2_watts:
        value_template: >-
          {{ state_attr('switch.k2_98', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      k3_watts:
        value_template: >-
          {{ state_attr('switch.k3_99', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      office_heater_watts:
        friendly_name: "Office Heater"
        value_template: >-
          {{ state_attr('switch.office_heater_37', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      office_humidifier_watts:
        friendly_name: "Office Humidifier"
        value_template: >-
          {{ state_attr('switch.humidifier_101', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      sump_watts:
        value_template: >-
          {{ state_attr('switch.sump_pump_20', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      dehumidifier_watts:
        value_template: >-
          {{ state_attr('switch.dehumidifier_110', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
  - platform: template
    sensors:
      battery_front_door_lock:
        friendly_name: "Front Door Lock Battery"
        value_template: '{{ states.lock.front_door_lock_10.attributes.battery_level }}'
        unit_of_measurement: "%"
  - platform: template
    sensors:
      washing_machine_watts:
        friendly_name: "Washing Machine Power"
        value_template: '{{ states.switch.washing_machine_107.attributes.current_power_w }}'
        unit_of_measurement: "W"
      washing_machine_status:
        friendly_name: "Washing Machine Status"
        value_template: >-
          {% if states('sensor.washing_machine_watts') | int > 400 %}
            Spin Cycle
          {% elif states('sensor.washing_machine_watts') | int > 5 %}
            Washing
          {% else %}
            Off
          {% endif %}

binary_sensor:
  # This monitors if my laptop is docked at my desk, which is a good proxy for
  # whether or not I'm sitting there.
  - platform: ping
    name: laptop-ethernet
    host: hajnal-ethernet.oneill.net

# Text to speech
tts:
  - platform: google_translate

input_boolean: !include input_boolean.yaml
#input_select: !include input_select.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
