default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "10.244.0.0/16"
    - "172.19.74.0/24"

# Enables configuration UI
config:

ios:

recorder:
  db_url: !env_var DB_URL

# Enables prometheus exporter
prometheus:
  namespace: hass

# Send notifications to Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
     - "-396790894"

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
- name: "telegram"
  platform: telegram
  chat_id: "-396790894"
- name: "opsgenie"
  platform: smtp
  sender: clayton@oneill.net
  recipient: email1@fnord.opsgenie.net
  server: smtp.gmail.com
  username: clayton.oneill@gmail.com
  password: !secret gmail_smtp_password
- name: "twilio_call"
  platform: twilio_call
  from_number: !secret twilio_number
- name: "twilio_sms"
  platform: twilio_sms
  from_number: !secret twilio_number
- name: "call_me"
  platform: group
  services:
  - service: twilio_call
    data:
      target: !secret my_phone
- name: "text_me"
  platform: group
  services:
  - service: twilio_sms
    data:
      target: !secret my_phone

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

lutron_caseta:
  - host: lutron-032e18fd.oneill.net
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

vera:
  vera_controller_url: http://172.19.74.180:3480
  exclude:
    # Office
    - 40 # office remote, dead battery, but might use one day, so not unpaired.
    - 66 # Motion sensor
    - 67 # Motion sensor 1
    - 68 # Motion sensor 2
    - 74 # Fake smoke sensor
    - 75 # Motion sensor 3
  lights:
    - 8  # Garage overhead lights
    - 19 # Office Floor Lamp
    - 106 # Main floor bathroom light

device_tracker:
  - platform: mqtt
    devices:
      clayton_phone_first_floor: "monitor/first-floor/claytons_phone/device_tracker"
      mary_phone_first_floor: "monitor/first-floor/marys_phone/device_tracker"
      paul_phone_first_floor: "monitor/first-floor/pauls_phone/device_tracker"

person:

logger:
  default: info

homekit:
  filter:
    include_entities: &entity_whitelist
    - cover.left_garage_door
    - cover.right_garage_door
    - light.bathroom_light_106
    - light.dining_room_light_108
    - light.family_room_standing_lamp_44
    - light.garage_overhead_lights_8
    - light.office_floor_lamp_19
    - light.office_light_76
    - light.office_sink_light
    - lock.front_door_lock_10
    - lock.garage_door_lock_88
    - sensor.garage_humidity
    - sensor.garage_temperature
    - sensor.netatmo_indoor_humidity
    - sensor.netatmo_indoor_temperature
    - sensor.netatmo_outdoor_humidity
    - sensor.netatmo_outdoor_temperature
    - switch.smoker_158
    - binary_sensor.family_room_humidifier_empty
    - binary_sensor.dining_room_humidifier_empty

    # Caseta items
    - light.basement_office_main_lights
    - switch.basement_stairs_main_lights
    - switch.exterior_basement_stairs_light
    - switch.guest_bathroom_exhaust_fan
    - light.guest_bathroom_vanity_lights
    - light.guest_bedroom_main_lights
    - light.guest_bedroom_floor_lamp
    - light.rec_room_main_lights
    - fan.master_bedroom_ceiling_fan
    - light.master_bedroom_ceiling_fan_light
    - light.rec_room_floor_lamp
    - light.office_floor_lamp
    - binary_sensor.office_occupancy
    - light.rec_room_back_right_floor_lamp
    - light.rec_room_front_left_floor_lamp

    # Harmony
    - switch.basement_tv
    - switch.appletv
    - switch.xbox
    - switch.playstation
    - switch.nintendo_switch

# Cloud
cloud:
  alexa:
    filter:
      include_entities: *entity_whitelist


mqtt:
  broker: mosquitto
  username: hass
  password: !secret mqtt_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

climate:
  - platform: generic_thermostat
    name: Office Thermostat
    heater: switch.office_heater
    target_sensor: sensor.office_bme280_temperature
    precision: 0.1
    min_temp: 60
    max_temp: 85
    hot_tolerance: 0

  - platform: generic_thermostat
    name: Office Foot Warmer
    heater: switch.office_foot_warmer_switch
    target_sensor: sensor.office_foot_warmer_temperature
    precision: 0.1
    min_temp: 60
    max_temp: 130
    hot_tolerance: 0


generic_hygrostat:
  - name: "Main Floor"
    humidifier: switch.main_floor_humidifiers
    target_sensor: sensor.living_room_humidity
    target_humidity: 40

cover:
  platform: opengarage
  covers:
    left_door:
      host: og-left-door.oneill.net
      device_key: !secret opengarage_device_key
      name: "Left Garage Door"
    right_door:
      host: og-right-door.oneill.net
      device_key: !secret opengarage_device_key
      name: "Right Garage Door"

light:
- platform: switch
  name: Office Sink Light
  entity_id: switch.office_sink
- platform: switch
  name: Office Closet Light
  entity_id: switch.office_closet_relay
- platform: group
  name: Office lights
  entities:
    - light.office_floor_lamp
    - light.basement_office_main_lights
    - light.office_sink_light
    - light.office_closet_light

switch:
- platform: template
  switches:
    basement_tv:
      friendly_name: "Basement TV"
      value_template: "{{ not is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Watch Apple TV"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
    appletv:
      friendly_name: "Apple TV"
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Apple TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Watch Apple TV"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
    xbox:
      friendly_name: "XBox"
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Xbox') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Play Xbox"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
    playstation:
      friendly_name: "Playstation"
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play PS5') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Play PS5"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
    nintendo_switch:
      friendly_name: "Nintendo Switch"
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Nintendo Switch') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Play Nintendo Switch"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub

    main_floor_humidifiers:
      friendly_name: "Main Floor Humidifiers"
      value_template: "{{ is_state('switch.dining_room_humidifier', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.dining_room_humidifier
        - service: switch.turn_on
          entity_id: switch.family_room_humidifier_relay
      turn_off:
        - service: switch.turn_off
          entity_id: switch.dining_room_humidifier
        - service: switch.turn_off
          entity_id: switch.family_room_humidifier_relay

# Sensors
sensor:
  - platform: template
    sensors:
      luser_watts:
        value_template: >-
          {{ state_attr('switch.luser_36', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      k2_watts:
        value_template: >-
          {{ state_attr('switch.k2_98', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      k3_watts:
        value_template: >-
          {{ state_attr('switch.k3_99', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      sump_watts:
        value_template: >-
          {{ state_attr('switch.sump_pump_20', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      dehumidifier_watts:
        value_template: >-
          {{ state_attr('switch.dehumidifier_110', 'current_power_w') | default(0) }}
        unit_of_measurement: "W"
      smoker_watts:
        value_template: '{{ states.switch.smoker_158.attributes.current_power_w }}'
        unit_of_measurement: "W"
  - platform: template
    sensors:
      battery_front_door_lock:
        friendly_name: "Front Door Lock Battery"
        value_template: '{{ states.lock.front_door_lock_10.attributes.battery_level }}'
        unit_of_measurement: "%"
  - platform: template
    # Airvisual sensors
    sensors:
      airvisual_co2:
        friendly_name: "Airvisual CO2"
        value_template: "{{  state_attr('air_quality.office_node_pro_air_quality', 'carbon_dioxide') | default(0) }}"
        unit_of_measurement: "ppm"
      airvisual_pm01:
        friendly_name: "Airvisual PM0.1"
        value_template: "{{  state_attr('air_quality.office_node_pro_air_quality', 'particulate_matter_0_1') | default(0) }}"
        unit_of_measurement: "ug/m3"
      airvisual_pm25:
        friendly_name: "Airvisual PM2.5"
        value_template: "{{  state_attr('air_quality.office_node_pro_air_quality', 'particulate_matter_2_5') | default(0) }}"
        unit_of_measurement: "ug/m3"
      airvisual_pm10:
        friendly_name: "Airvisual PM10"
        value_template: "{{  state_attr('air_quality.office_node_pro_air_quality', 'particulate_matter_10') | default(0) }}"
        unit_of_measurement: "ug/m3"
      airvisual_pm25_sensor_life:
        friendly_name: "Airvisual PM2.5 Sensor Life"
        value_template: "{{  state_attr('air_quality.office_node_pro_air_quality', 'pm2_5_sensor_life') | default(0) }}"
        unit_of_measurement: "ug/m3"

binary_sensor:
  # This monitors if my laptop is docked at my desk, which is a good proxy for
  # whether or not I'm sitting there.
  - platform: ping
    name: laptop-ethernet
    host: hajnal-ethernet.oneill.net
  - platform: workday
    country: US
  - platform: template
    sensors:
      freezer_too_warm:
        device_class: problem
        delay_on: "00:20:00"
        value_template: >
          {{ states("sensor.freezer_temperature") | float(999.0) == 999.0
             or states("sensor.freezer_temperature") | float > 20 }}'

      main_floor_humidity_low:
        value_template: >
          {{ state_attr('sensor.main_floor_humidifier', 'humidity') | float(999.0) >
               states('sensor.living_room_humidity') | float(0.0)
          }}
      family_room_humidifier_empty:
        friendly_name: "Family Room Humidifier Empty"
        device_class: problem
        value_template: >
          {{ states("main_floor_humidity_low")
               and states("switch.family_room_humidifier_relay")
               and states("sensor.family_room_humidifier_power") |float(0.0) < 1.0
          }}

      dining_room_humidifier_empty:
        friendly_name: "Dining Room Humidifier Empty"
        device_class: problem
        value_template: >
          {{ states("main_floor_humidity_low")
               and states("switch.dining_room_humidifier")
               and states("sensor.dining_room_humidifier_electric_consumption_w") |float(0.0) < 1.0
          }}


alert:
  basement_sump_water:
    name: "Water is detected in the basement near the sump!"
    entity_id: binary_sensor.water_sensor_157
    state: "on"
    repeat: 10
    notifiers:
    - call_me
  basement_back_door_water:
    name: "Water is detected in the basement near the back door!"
    entity_id: binary_sensor.basement_door_water_159
    state: "on"
    repeat: 10
    notifiers:
    - call_me
  computer_room_water:
    name: "Water is detected in the computer room!"
    entity_id: binary_sensor.computer_room_water_sensor_water_alarm_water_leak_detected
    state: "on"
    repeat: 10
    notifiers:
    - call_me
  storage_room_water:
    name: "Water is detected in the storage room!"
    entity_id: binary_sensor.storage_water_sensor_170
    state: "on"
    repeat: 10
    notifiers:
    - call_me
  freezer_too_warm:
    name: "Temperature in the freezer is too warm!"
    entity_id: binary_sensor.freezer_too_warm
    state: "on"
    repeat: 10
    notifiers:
    - call_me

  freezer_sensor_offline:
    name: "Freezer sensor is offline"
    entity_id: binary_sensor.freezer_sensor_status
    state: "off"
    repeat: 10
    skip_first: true
    notifiers:
    - call_me

# Text to speech
tts:
  - platform: google_translate

input_boolean: !include input_boolean.yaml
#input_select: !include input_select.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
