---
office:
  name: Office
  entities:
    - switch.desk_43
    - switch.office_heater_37
    - light.office_light_76
    - light.office_floor_lamp_19
    - switch.humidifier_101
    - climate.auto_virtual_thermos_100
danger:
  name: "Danger"
  view: true
  control: hidden
  entities:
    - switch.luser_36
    - switch.k2_98
    - switch.k3_99
    - switch.sump_pump_20
    - switch.washing_machine_107

