maeves_phone:
  hide_if_away: false
  icon:
  mac: 30:D9:D9:33:85:81
  name: "Maeve's Phone"
  picture:
  track: true

zoes_phone:
  hide_if_away: false
  icon:
  mac: A4:B8:05:BB:B0:5B
  name: "Zoe's Phone"
  picture:
  track: true

claytons_phone:
  hide_if_away: false
  icon:
  mac: F0:99:B6:53:06:A1
  name: "Clayton's Phone"
  picture:
  track: true

claytons_watch:
  hide_if_away: false
  icon:
  mac: 68:FE:F7:42:6E:93
  name: "Clayton's Watch"
  picture:
  track: true

clayton_phone_first_floor:
  hide_if_away: false
  name: "Clayton's phone first floor"
  track: true

pauls_phone:
  hide_if_away: false
  icon:
  mac: 38:53:9c:94:de:7b
  name: "Paul's Phone"
  picture:
  track: true

marys_phone:
  hide_if_away: false
  icon:
  mac: C0:A5:3E:27:33:08
  name: "Mary's Phone"
  picture:
  track: true

mary_phone_first_floor:
  hide_if_away: false
  name: "Mary's phone first floor"
  track: true

paul_phone_first_floor:
  hide_if_away: false
  name: "Paul's phone first floor"
  track: true
