substitutions:
  devicename: drybox-bme280
  device_id: drybox_bme280
  human_devicename: Drybox BME280
  icon: mdi:coolant-temperature

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  d1_mini_bme280: !include common/device-classes/d1_mini_bme280.yaml
