substitutions:
  devicename: k4-power
  device_id: k4_power
  human_devicename: K4
  icon: mdi:ship-wheel

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/sonoff_s31.yaml

